//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rainbowjanakpuriEntities : DbContext
    {
        public rainbowjanakpuriEntities()
            : base("name=rainbowjanakpuriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassSubjectMap> ClassSubjectMaps { get; set; }
        public virtual DbSet<Examination> Examinations { get; set; }
        public virtual DbSet<GradeEntry> GradeEntries { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MarksEntry> MarksEntries { get; set; }
        public virtual DbSet<MiscEntry> MiscEntries { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SM> SMS { get; set; }
        public virtual DbSet<SMSEntry> SMSEntries { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentCategory> StudentCategories { get; set; }
        public virtual DbSet<StudentLeaveType> StudentLeaveTypes { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
