//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Attendances = new HashSet<Attendance>();
            this.GradeEntries = new HashSet<GradeEntry>();
            this.MarksEntries = new HashSet<MarksEntry>();
            this.MiscEntries = new HashSet<MiscEntry>();
        }
    
        public int Id { get; set; }
        public int StudentCategoryId { get; set; }
        public int ClassId { get; set; }
        public int AdmissionNo { get; set; }
        public string StudentName { get; set; }
        public string FatherName { get; set; }
        public string FatherMobileNumber { get; set; }
        public string MotherName { get; set; }
        public bool Gender { get; set; }
        public string Address { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<int> SiblingAdmissionNo { get; set; }
        public string AadharCard { get; set; }
        public string BirthCertificate { get; set; }
        public string TransferCertificate { get; set; }
        public string Miscellaneous1Name { get; set; }
        public string Miscellaneous1Link { get; set; }
        public string Miscellaneous2Name { get; set; }
        public string Miscellaneous2Link { get; set; }
        public string Miscellaneous3Name { get; set; }
        public string Miscellaneous3Link { get; set; }
        public string DeletedTransferCertificate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradeEntry> GradeEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarksEntry> MarksEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiscEntry> MiscEntries { get; set; }
        public virtual StudentCategory StudentCategory { get; set; }
    }
}
